### ISSUE TITLE
Benchmark quotient is flipped

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaEarth/Cartography.jl#42]
I think it should be `Proj.jl / Cartography.jl`

| CRS	| DIRECTION	| Proj.jl	| Cartography.jl	| Cartography.jl / Proj.jl |
|:-- |:-- |:--|:--|:--|
| Lambert	| forward	| 8.05894519131334e-8	|	2.214e-9	| 36.4 |

**Comment by juliohm** [comment]
Thanks for reporting. It is a typo in the column name. The result is correct, but the column is named incorrectly.

**Comment by juliohm** [comment]
Fixed on master.
