### ISSUE TITLE
Invoking cartography methods without Unitful directly attached to point types

### ISSUE THREAD

**Issue by asinghvi17** [JuliaEarth/Cartography.jl#43]
Hey!  This looks like a really cool package, and native Julia projections are something I've wanted to introduce to GeoMakie for a while.

Is it possible to apply these transformations in a generic way, without converting between types?  

That would simplify the interface considerably for me.  For example, treating CRS types in a trait-like way with function signatures like `convert(point, source_crs, dest_crs)` or maybe a constructed Transformation object that can be called on any pointlike type would make allowing this in GeoMakie pretty easy and fast.

Also, have you considered tying in to https://github.com/JuliaGeo/GeoFormatTypes.jl?  They are already integrated in th raster data space so it would be nice to be able to apply these types to other coordinates, even if it's just as an extension package to accept GeoFormatTypes and convert them to Cartography.jl types.

**Comment by juliohm** [comment]
The design we came up with here has very specific use cases in mind, which don't include the trait-like interface proposed. Transformation objects are planned, with a well-defined interface that already exists in the stack we are building.

Regarding GeoFormatTypes.jl, we see them as a means to improve GeoIO.jl load/save and nothing more. We will only work on it after we finish some more urgent work in the stack.

**Comment by asinghvi17** [comment]
As long as transformation-like objects exist which can consume generic points, this is usable for me :)
